ras_challenges = [
  {
    title: "Raspberry Pi Operating System",
    description: "Name one operating system that can be run on a Raspberry Pi?",
    type: "input",
    solution: "Raspberry Pi OS",
  },
  {
    title: "Programming Languages",
    description: "Name one programming language that is used with Raspberry Pi",
    type: "input",
    solution: "Python",
  },
  {
    title: "Raspberry Pi Connectivity",
    description:
      "Name one method of connectivity supported by the Raspberry Pi.",
    type: "input",
    solution: "Wifi",
  },
  {
    title: "GPIO Purpose",
    description:
      "What is the main purpose of the GPIO pins on the Raspberry Pi?",
    type: "input",
    solution: "connecting electronic components",
  },
  {
    title: "Raspberry Pi Imager OS",
    description:
      "Name one of the operating systems that can be selected using Raspberry Pi Imager.",
    type: "input",
    solution: "Debian",
  },
  {
    title: "SSH access type",
    description: "What type of access does SSH provide to the Raspberry Pi?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Graphical Interface",
      "Command Line",
      "Remote File Access",
    ],
    solution: "Command Line",
  },
  {
    title: "VNC access type",
    description: "What type of access does VNC provide to the Raspberry Pi?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Command Line",
      "Full Graphical Desktop Access",
      "Text-Based Interface",
    ],
    solution: "Full Graphical Desktop Access",
  },{
    title: "Basic Linux Command: pwd",
    description: "What does the basic Linux command 'pwd' do?",
    type: "select",
    options: ["Select Correct Answer", "Print working directory", "List files and folders", "Change file permissions"],
    solution: "Print working directory",
},
{
    title: "Basic Linux Command: ls",
    description: "What does the basic Linux command 'ls' do?",
    type: "select",
    options: ["Select Correct Answer", "Show current directory", "List files and folders", "Make a file executable"],
    solution: "List files and folders",
},
{
    title: "Basic Linux Command: chmod",
    description: "What is the purpose of the Linux command 'chmod +x script.py'?",
    type: "select",
    options: ["Select Correct Answer", "Make a file executable", "Print working directory", "Delete a file"],
    solution: "Make a file executable",
},
  {
    title: "Processor Type",
    description: "What type of processor does the Raspberry Pi use?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Microcontroller",
      "Dual Core Processor",
      "Full CPU",
    ],
    solution: "Full CPU",
  },
  {
    title: "Graphical User Interface",
    description: "Does the Raspberry Pi have a graphical user interface?",
    type: "select",
    options: ["Select Correct Answer", "Yes", "No"],
    solution: "Yes",
  },
  {
    title: "Cost Comparison",
    description:
      "Compared to an Arduino, is the cost of the Raspberry Pi higher or lower?",
    type: "select",
    options: ["Select Correct Answer", "Higher", "Lower", "Same"],
    solution: "Higher",
  },
  {
    title: "Primary Use Case",
    description: "Which of these is a primary use case for a Raspberry Pi?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Real-time Control",
      "IoT, Robotics, AI",
      "Single Program Runs",
    ],
    solution: "IoT, Robotics, AI",
  },
  {
    title: "Home Automation",
    description:
      "In a home automation setup, what is used to interface with a light sensor?",
    type: "select",
    options: ["Select Correct Answer", "Relay", "Breadboard", "PIR Sensor"],
    solution: "Breadboard",
  },
  {
    title: "Web Server Suitability",
    description:
      "Is a Raspberry Pi suitable for large-scale web server projects?",
    type: "select",
    options: ["Select Correct Answer", "Yes", "No", "Sometimes"],
    solution: "No",
  },
  {
    title: "Personal Cloud Storage",
    description:
      "Which of these is an example of using a Raspberry Pi as a web server?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Personal cloud storage",
      "Gaming Emulator",
      "Home Automation",
    ],
    solution: "Personal cloud storage",
  },
  {
    title: "Gaming on Raspberry Pi",
    description: "What software enables gaming emulation on the Raspberry Pi?",
    type: "select",
    options: ["Select Correct Answer", "Raspberry Pi OS", "RetroPie", "Ubuntu"],
    solution: "RetroPie",
  },
  {
    title: "Micro SD Card Location",
    description: "Where is the micro SD card located on the Raspberry Pi?",
    type: "select",
    options: ["Select Correct Answer", "Top", "Underneath", "Side"],
    solution: "Underneath",
  },
  {
    title: "Connection Ports",
    description: "Which port is used to connect a monitor to the Raspberry Pi?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Ethernet port",
      "HDMI port",
      "USB ports",
    ],
    solution: "HDMI port",
  },
  {
    title: "Power Port",
    description: "Which port is used to power the Raspberry Pi?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Micro USB",
      "Audio jack",
      "Camera Module port",
    ],
    solution: "Micro USB",
  },
  {
    title: "Initial Setup Connection Type",
    description:
      "Which connection type is ideal for initial setup of the Raspberry Pi?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Keyboard, Mouse, Monitor",
      "SSH",
      "VNC",
    ],
    solution: "Keyboard, Mouse, Monitor",
  },
  {
    title: "Headless Setup",
    description:
      "Which connection method is best for a headless setup of the Raspberry Pi?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Keyboard, Mouse, Monitor",
      "SSH",
      "VNC",
    ],
    solution: "SSH",
  },
  {
    title: "Remote Desktop Access",
    description:
      "Which connection method provides full graphical desktop access?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Keyboard, Mouse, Monitor",
      "SSH",
      "VNC",
    ],
    solution: "VNC",
  },
  {
    title: "SSH Operating System",
    description: "On which OS can you use SSH to access a Raspberry Pi",
    type: "select",
    options: [
      "Select Correct Answer",
      "Windows",
      "macOS",
      "Linux",
      "All of the above",
    ],
    solution: "All of the above",
  },
  {
    title: "VNC Bandwidth",
    description: "Does VNC require more or less bandwidth than SSH?",
    type: "select",
    options: ["Select Correct Answer", "More", "Less", "Same"],
    solution: "More",
  },
  {
    title: "Basic Linux Command: cd",
    description: "What does the basic linux command 'cd' do?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Create an empty file",
      "Move into a directory",
      "Delete a file",
    ],
    solution: "Move into a directory",
  },
  {
    title: "Basic Linux Command: touch",
    description: "What does the basic linux command 'touch' do?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Create an empty file",
      "Edit a file in the terminal",
      "Show the file content",
    ],
    solution: "Create an empty file",
  },
  {
    title: "Basic Linux Command: cat",
    description: "What does the basic linux command 'cat' do?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Create an empty file",
      "Edit a file in the terminal",
      "Show the file content",
    ],
    solution: "Show the file content",
  },
  {
    title: "Basic Linux Command: rm",
    description: "What does the basic linux command 'rm' do?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Create a new folder",
      "Delete an empty folder",
      "Delete a file",
    ],
    solution: "Delete a file",
  },
  {
    title: "Basic Linux Command: mkdir",
    description: "What does the basic linux command 'mkdir' do?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Create a new folder",
      "Delete an empty folder",
      "Delete a file",
    ],
    solution: "Create a new folder",
  },
  {
    title: "Basic Linux Command: rmdir",
    description: "What does the basic linux command 'rmdir' do?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Create a new folder",
      "Delete an empty folder",
      "Delete a file",
    ],
    solution: "Delete an empty folder",
  },
  {
    title: "File Permissions: echo",
    description: "What does the linux command 'echo' do?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Write the output of a command into a file",
      "Change ownership of a file",
      "print 'something' in the console",
    ],
    solution: "print 'something' in the console",
  },
  {
    title: "File Permissions: >",
    description: "What does the linux command '>' do?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Write the output of a command into a file",
      "Change ownership of a file",
      "Make a file executable",
    ],
    solution: "Write the output of a command into a file",
  },
  {
    title: "File Permissions: chmod 755",
    description: "What does the linux command 'chmod 755' do?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Make a file executable",
      "Give read/write/execute to owner, read/execute to others",
      "Change ownership of a file",
    ],
    solution: "Give read/write/execute to owner, read/execute to others",
  },
  {
    title: "File Permissions: sudo chown",
    description: "What does the linux command 'sudo chown' do?",
    type: "select",
    options: [
      "Select Correct Answer",
      "Make a file executable",
      "Give read/write/execute to owner, read/execute to others",
      "Change ownership of a file",
    ],
    solution: "Change ownership of a file",
  },
];
module.exports = ras_challenges;
